### ISSUE TITLE
Support version 7 of the CLI

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/cf-service-connect#56]
This plugin does not work with the newest version of the CLI.

Another option is to remove this plugin and direct people to https://github.com/alphagov/paas-cf-conduit provided this plugin works w/ version 7. This project seems to be more actively developed and supported.

## Security considerations

none

**Comment by karareinsel** [comment]
@spgreenberg can you provide a little more context about the relative priority and level of effort to implement?

**Comment by afeld** [comment]
Error I'm seeing, to help others find this issue:

```
bad CPU type in executable
File is not a valid cf CLI plugin binary.
FAILED
```

**Comment by mheadd** [comment]
Is this still an issue? I don't seem to have any issues connecting using this plugin with cli V7.

<img width="747" alt="Screen Shot 2021-02-10 at 3 36 04 PM" src="https://user-images.githubusercontent.com/58419/107569281-22620080-6bb6-11eb-8854-aa49b6b769ec.png">

Possible worth noting that both the app and service I'm using here were both pushed and created with V7.

**Comment by rahearn** [comment]
FWIW, I'm pretty sure I had previously had an issue with this not working with cf-cli@7, but I just retried with `7.2.0+be4a5ce2b.2020-12-10` and it worked with an app that was last pushed with v6, and a service created with terraform.

**Comment by mheadd** [comment]
@rahearn Thanks. I remember having an issue too, and others reported it as well.

**Comment by mheadd** [comment]
Closing since this issue seems to be resolved.
