### ISSUE TITLE
Update CI/CD integration to use Concourse for new project builds

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/cf-service-connect#60]
In order to have proper CI/CD integration, we should shift this project to integrate with Concourse for future builds.

## Acceptance Criteria
* [ ] GIVEN this repo, WHEN a PR is merged to update the plugin, THEN a build should be kicked off in Concourse AND a new Go binary produced that customers and platform operators can install for the cf CLI.

--- 

## Security Considerations
- This integration with Concourse would bring this project in line with our other work

## Implementation sketch
* [ ] Create a `ci` directory and a `pipeline.yml` file inside of it for Concourse (draw some circles...)
* [ ] Figure out how to build a Go binary as an output in Concourse (...draw the rest of the owl)

**Comment by markdboyd** [comment]
Closed by https://github.com/cloud-gov/cf-service-connect/pull/70
